version: '3'
services:
  ###> doctrine/doctrine-bundle ###
  database:
      image: postgres:${POSTGRES_VERSION:-15}-alpine
      platform: linux/amd64
      restart: always
      ports:
        - 54320:5432
      environment:
          #POSTGRES_DB: ${POSTGRES_DB:-iquadrat}
          # You should definitely change the password in production
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
          #POSTGRES_USER: ${POSTGRES_USER:-iquadrat}